name: Run Pylint on pull request

on: [pull_request]

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install pylint
        run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir pylint
      - name: Install dependencies
        run: |
        pip install --no-cache-dir numpy pygame PyOpenGL PyOpenGL-accelerate
      - name: Lint
        run: |
        pylint -E --rcfile=.pylintrc --extension-pkg-whitelist=pygame *.py
